package ar.edu.unlam.pb2.carritoDeCompras.dominio;

public enum CategoriaDeProducto {

	CALZADO,
	CELULARES_Y_SMARTPHONES,
	CAMARAS_Y_ACCESORIOS,
	CONSOLAS_Y_VIDEOJUEGOS,
	COMPUTACION,
	ELECTRONICA_AUDIO_VIDEO,
	TELEVISORES,
	AIRES_ACONDICIONADO,
	CALEFACCION,
	HELADERA,
	LAVARROPAS,
	COCINAS
}