package ar.edu.unlam.pb2.empleados.dominio;

public enum Departamento {

	DIRECCION_GENERAL,
	SISTEMAS_DE_INFORMACION,
	TECNOLOGIA_DE_NEGOCIO,
	INFRAESTRUCTURAS_E_INSTALACIONES,
	OPERACIONES_DE_SISTEMAS,
	GESTION_DEL_CLIENTE_INTERNO,
	COMERCIAL,
	VENTAS,
	RECURSOS_HUMANOS,
}